package com.zhuoketeam.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhuoketeam.greendaodemo.bean.ClassRoom;
import com.zhuoketeam.greendaodemo.bean.Student;

import com.zhuoketeam.greendaodemo.db.ClassRoomDao;
import com.zhuoketeam.greendaodemo.db.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classRoomDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final ClassRoomDao classRoomDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classRoomDaoConfig = daoConfigMap.get(ClassRoomDao.class).clone();
        classRoomDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        classRoomDao = new ClassRoomDao(classRoomDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(ClassRoom.class, classRoomDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        classRoomDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public ClassRoomDao getClassRoomDao() {
        return classRoomDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
